plays(bob, guitar).
plays(ted, guitar).
plays(ted, bass).
plays(ann, sax).
plays(sue, trumpet).
plays(jim, bass).
plays(jim, keyboard).
plays(jen, drums).
plays(jen, xylophone).

genre(bob, rock).
genre(bob, metal).
genre(ted, blues).
genre(ann, jazz).
genre(sue, jazz).
genre(jim, rock).
genre(jim, metal).
genre(jim, jazz).
genre(jen, rock).
genre(jen, metal).
genre(jen, jazz).
genre(jen, classical).